/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nc_gs_io_UTF8Util */

#ifndef _Included_com_nc_gs_io_UTF8Util
#define _Included_com_nc_gs_io_UTF8Util

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    tryUnpackAscii
 * Signature: (J[C)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToArray
  (JNIEnv *, jclass, jlong, jcharArray);

/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8ToUtf16Raw
 * Signature: (JJI)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToAddress
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
