/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nc_gs_io_UTF8Util */

#ifndef _Included_com_nc_gs_io_UTF8Util
#define _Included_com_nc_gs_io_UTF8Util

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8ToArrayAVX
 * Signature: (J[C)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToArrayAVX
  (JNIEnv *, jclass, jlong, jcharArray);

/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8ToArrayAVX
 * Signature: (J[C)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToArrayAVX512
  (JNIEnv *, jclass, jlong, jcharArray);

/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8ToArray
 * Signature: (J[C)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToArray
  (JNIEnv *, jclass, jlong, jcharArray);

/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8ToAddress
 * Signature: (JJI)I
 */
JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_utf8ToAddress
  (JNIEnv *, jclass, jlong, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_nc_gs_io_UTF8Util_compilationFlags
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
